// frontend/src/pages/clients/ClientDetail.tsx
import { useState } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, Edit2, Phone, Mail, MapPin, CreditCard, AlertTriangle, Car } from 'lucide-react';
import { clientsApi } from '../../api/clients';
import Spinner from '../../components/ui/Spinner';
import Button from '../../components/ui/Button';
import { BlacklistedBadge, ContractBadge, SeverityBadge, IncidentTypeBadge } from '../../components/ui/Badge';

const tabs = ['Información', 'Contratos', 'Incidencias'] as const;

export default function ClientDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [tab, setTab] = useState<(typeof tabs)[number]>('Información');

  const { data, isPending } = useQuery({
    queryKey: ['client', id],
    queryFn: () => clientsApi.getHistory(Number(id)).then((r) => r.data),
  });

  if (isPending) return <div className="p-8"><Spinner /></div>;
  if (!data) return null;

  return (
    <div className="p-8">
      {/* Back + actions */}
      <div className="flex items-center gap-4 mb-6">
        <button onClick={() => navigate(-1)} className="text-gray-400 hover:text-gray-600">
          <ArrowLeft size={20} />
        </button>
        <div className="flex-1">
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-bold text-gray-900">{data.name}</h1>
            {data.isBlacklisted && <BlacklistedBadge />}
          </div>
        </div>
        <Link to={`/clients/${id}/edit`}>
          <Button variant="secondary">
            <Edit2 size={14} />
            Editar
          </Button>
        </Link>
      </div>

      {/* Blacklist warning */}
      {data.isBlacklisted && (
        <div className="mb-6 flex items-start gap-3 bg-gray-900 rounded-xl px-5 py-4">
          <AlertTriangle size={18} className="text-gray-400 mt-0.5 flex-shrink-0" />
          <div>
            <p className="font-semibold text-white">Cliente en lista negra</p>
            <p className="text-sm text-gray-400 mt-0.5">
              Este cliente tiene incidencias graves sin resolver. Revisa su historial antes de aceptar nuevos contratos.
            </p>
          </div>
        </div>
      )}

      {/* Tabs */}
      <div className="flex gap-1 border-b border-gray-200 mb-6">
        {tabs.map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-4 py-2.5 text-sm font-medium border-b-2 -mb-px transition-colors ${
              tab === t
                ? 'border-gray-900 text-gray-900'
                : 'border-transparent text-gray-500 hover:text-gray-700'
            }`}
          >
            {t}
          </button>
        ))}
      </div>

      {/* Tab: Info */}
      {tab === 'Información' && (
        <div className="grid grid-cols-2 gap-6">
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6 space-y-4">
            <h3 className="font-semibold text-gray-900">Datos personales</h3>
            <InfoRow icon={CreditCard} label="DNI" value={(data as { dni?: string }).dni ?? '—'} />
            <InfoRow icon={Mail} label="Email" value={(data as { email?: string }).email ?? '—'} />
            <InfoRow icon={Phone} label="Teléfono" value={(data as { phone?: string }).phone ?? '—'} />
            <InfoRow icon={MapPin} label="Dirección" value={(data as { address?: string }).address ?? '—'} />
          </div>
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
            <h3 className="font-semibold text-gray-900 mb-4">Resumen</h3>
            <div className="grid grid-cols-2 gap-4">
              <StatBox value={data.contracts?.length ?? 0} label="Contratos" color="bg-gray-100 text-gray-700" />
              <StatBox value={data.incidents?.length ?? 0} label="Incidencias" color="bg-gray-100 text-gray-700" />
              <StatBox
                value={data.incidents?.filter((i: { resolved: boolean }) => !i.resolved).length ?? 0}
                label="Sin resolver"
                color="bg-gray-900 text-white"
              />
              <StatBox
                value={data.contracts?.filter((c: { carReturn: unknown }) => !c.carReturn).length ?? 0}
                label="Sin devolver"
                color="bg-gray-800 text-white"
              />
            </div>
          </div>
        </div>
      )}

      {/* Tab: Contratos */}
      {tab === 'Contratos' && (
        <div className="space-y-3">
          {(!data.contracts || data.contracts.length === 0) ? (
            <p className="text-gray-400 text-sm py-8 text-center">Sin contratos registrados</p>
          ) : (
            data.contracts.map((c: { id: number; car: { licensePlate: string; brand: string; model: string }; startDate: string; endDate: string; status: string; carReturn: unknown }) => (
              <div key={c.id} className="bg-white rounded-xl border border-gray-200 p-4 flex items-center gap-4">
                <Car size={18} className="text-gray-400" />
                <div className="flex-1">
                  <p className="font-medium text-gray-900">{c.car.brand} {c.car.model} · {c.car.licensePlate}</p>
                  <p className="text-xs text-gray-400">
                    {new Date(c.startDate).toLocaleDateString('es-ES')} → {new Date(c.endDate).toLocaleDateString('es-ES')}
                  </p>
                </div>
                <ContractBadge status={c.status as 'ACTIVE' | 'COMPLETED' | 'CANCELLED' | 'OVERDUE'} />
                {!c.carReturn && c.status === 'ACTIVE' && (
                  <Link to={`/car-returns/new?contractId=${c.id}`}>
                    <Button variant="success" size="sm">Registrar devolución</Button>
                  </Link>
                )}
                <Link to={`/rentals/${c.id}`} className="text-gray-500 hover:text-gray-900 text-xs">Ver →</Link>
              </div>
            ))
          )}
        </div>
      )}

      {/* Tab: Incidencias */}
      {tab === 'Incidencias' && (
        <div className="space-y-3">
          {(!data.incidents || data.incidents.length === 0) ? (
            <p className="text-gray-400 text-sm py-8 text-center">Sin incidencias</p>
          ) : (
            data.incidents.map((i: { id: number; type: string; description: string; severity: string; resolved: boolean; createdAt: string }) => (
              <div key={i.id} className="bg-white rounded-xl border border-gray-200 p-4">
                <div className="flex items-start justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <IncidentTypeBadge type={i.type as 'PAYMENT' | 'DAMAGE' | 'NOT_RETURNED' | 'LATE_RETURN' | 'THEFT' | 'ACCIDENT' | 'OTHER'} />
                    <SeverityBadge severity={i.severity as 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'} />
                    {i.resolved && (
                      <span className="text-xs text-gray-500 bg-gray-100 px-2 py-0.5 rounded-full font-medium">Resuelta</span>
                    )}
                  </div>
                  <p className="text-xs text-gray-400">{new Date(i.createdAt).toLocaleDateString('es-ES')}</p>
                </div>
                <p className="text-sm text-gray-700">{i.description}</p>
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
}

function InfoRow({ icon: Icon, label, value }: { icon: React.ElementType; label: string; value: string }) {
  return (
    <div className="flex items-center gap-3">
      <Icon size={16} className="text-gray-400 flex-shrink-0" />
      <div>
        <p className="text-xs text-gray-400">{label}</p>
        <p className="text-sm font-medium text-gray-800">{value}</p>
      </div>
    </div>
  );
}

function StatBox({ value, label, color }: { value: number; label: string; color: string }) {
  return (
    <div className={`rounded-xl p-3 text-center ${color}`}>
      <p className="text-2xl font-bold">{value}</p>
      <p className="text-xs mt-0.5">{label}</p>
    </div>
  );
}

// frontend/src/app/features/clients/client-detail.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DatePipe, DecimalPipe } from '@angular/common';
import { LucideAngularModule, ArrowLeft, User, Car, FileText, AlertTriangle, MapPin, Phone, Mail, CreditCard } from 'lucide-angular';
import { ClientsService } from '../../core/services/clients.service';
import { SpinnerComponent } from '../../shared/components/spinner.component';
import { BlacklistedBadgeComponent, ContractBadgeComponent, SeverityBadgeComponent, IncidentTypeBadgeComponent } from '../../shared/components/badge.component';
import type { CarCondition, ContractStatus, IncidentType, Severity } from '../../core/models';

interface ClientDetail {
  id: number;
  name: string;
  email: string;
  phone: string;
  dni: string;
  address?: string;
  notes?: string;
  isBlacklisted: boolean;
  blacklistReason?: string;
  blacklistedAt?: string;
  createdAt: string;
  cars: Array<{ id: number; licensePlate: string; brand: string; model: string; year: number; color?: string }>;
  contracts: Array<{
    id: number;
    startDate: string;
    endDate: string;
    status: ContractStatus;
    totalPrice: number;
    notes?: string;
    createdAt: string;
    car: { id: number; licensePlate: string; brand: string; model: string; year: number };
    carReturn?: { returnDate: string; onTime: boolean; condition: CarCondition; damagesFound: boolean };
  }>;
  incidents: Array<{
    id: number;
    type: IncidentType;
    severity: Severity;
    description: string;
    resolved: boolean;
    resolvedAt?: string;
    createdAt: string;
    contract?: { id: number; car: { licensePlate: string; brand: string; model: string } };
  }>;
}

@Component({
  selector: 'app-client-detail',
  standalone: true,
  imports: [
    RouterLink, DatePipe, DecimalPipe, LucideAngularModule,
    SpinnerComponent, BlacklistedBadgeComponent, ContractBadgeComponent,
    SeverityBadgeComponent, IncidentTypeBadgeComponent,
  ],
  template: `
    <div class="flex items-center gap-3 mb-6">
      <a routerLink="/clients" class="p-2 rounded-lg hover:bg-gray-200 transition-colors text-gray-500">
        <lucide-icon [img]="ArrowLeft" [size]="16"></lucide-icon>
      </a>
      <h1 class="text-xl font-semibold text-gray-900">Ficha del cliente</h1>
    </div>

    @if (loading()) {
      <app-spinner></app-spinner>
    } @else if (client()) {
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-5">

        <!-- Columna izquierda: datos del cliente -->
        <div class="space-y-5">
          <div class="card p-6">
            <div class="flex items-center gap-3 mb-5">
              <div class="w-10 h-10 rounded-xl bg-gray-100 flex items-center justify-center flex-shrink-0">
                <lucide-icon [img]="User" [size]="18" class="text-gray-500"></lucide-icon>
              </div>
              <div>
                <h2 class="text-base font-semibold text-gray-900">{{ client()!.name }}</h2>
                @if (client()!.isBlacklisted) {
                  <app-blacklisted-badge></app-blacklisted-badge>
                }
              </div>
            </div>
            <dl class="space-y-3 text-sm">
              <div class="flex items-center gap-2 text-gray-600">
                <lucide-icon [img]="CreditCard" [size]="13" class="text-gray-400 flex-shrink-0"></lucide-icon>
                <span class="font-mono">{{ client()!.dni }}</span>
              </div>
              <div class="flex items-center gap-2 text-gray-600">
                <lucide-icon [img]="Mail" [size]="13" class="text-gray-400 flex-shrink-0"></lucide-icon>
                <span>{{ client()!.email }}</span>
              </div>
              <div class="flex items-center gap-2 text-gray-600">
                <lucide-icon [img]="Phone" [size]="13" class="text-gray-400 flex-shrink-0"></lucide-icon>
                <span>{{ client()!.phone }}</span>
              </div>
              @if (client()!.address) {
                <div class="flex items-start gap-2 text-gray-600">
                  <lucide-icon [img]="MapPin" [size]="13" class="text-gray-400 flex-shrink-0 mt-0.5"></lucide-icon>
                  <span>{{ client()!.address }}</span>
                </div>
              }
            </dl>
            @if (client()!.notes) {
              <div class="mt-4 pt-4 border-t border-gray-100">
                <p class="text-xs text-gray-400 mb-1">Notas</p>
                <p class="text-sm text-gray-600">{{ client()!.notes }}</p>
              </div>
            }
            @if (client()!.isBlacklisted && client()!.blacklistReason) {
              <div class="mt-4 pt-4 border-t border-gray-100">
                <p class="text-xs text-red-400 mb-1">Motivo blacklist</p>
                <p class="text-sm text-red-700">{{ client()!.blacklistReason }}</p>
              </div>
            }
            <p class="text-xs text-gray-300 mt-5">Cliente desde {{ client()!.createdAt | date:'dd/MM/yyyy' }}</p>
          </div>

          <!-- Vehículos asignados -->
          <div class="card p-5">
            <div class="flex items-center gap-2 mb-4">
              <lucide-icon [img]="Car" [size]="15" class="text-gray-400"></lucide-icon>
              <h3 class="text-sm font-semibold text-gray-700">Vehículos asignados</h3>
              <span class="ml-auto text-xs text-gray-400">{{ client()!.cars.length }}</span>
            </div>
            @if (client()!.cars.length === 0) {
              <p class="text-sm text-gray-400">Sin vehículos asignados</p>
            } @else {
              <div class="space-y-2">
                @for (car of client()!.cars; track car.id) {
                  <a [routerLink]="['/cars']" class="flex items-center gap-3 p-2.5 rounded-lg hover:bg-gray-50 transition-colors">
                    <div class="w-7 h-7 rounded-lg bg-gray-100 flex items-center justify-center flex-shrink-0">
                      <lucide-icon [img]="Car" [size]="12" class="text-gray-500"></lucide-icon>
                    </div>
                    <div>
                      <p class="text-sm font-medium text-gray-900">{{ car.brand }} {{ car.model }}</p>
                      <p class="text-xs font-mono text-gray-400">{{ car.licensePlate }} · {{ car.year }}</p>
                    </div>
                  </a>
                }
              </div>
            }
          </div>
        </div>

        <!-- Columna derecha: contratos e incidencias -->
        <div class="lg:col-span-2 space-y-5">

          <!-- Contratos -->
          <div class="card p-5">
            <div class="flex items-center gap-2 mb-4">
              <lucide-icon [img]="FileText" [size]="15" class="text-gray-400"></lucide-icon>
              <h3 class="text-sm font-semibold text-gray-700">Contratos</h3>
              <span class="ml-auto text-xs text-gray-400">{{ client()!.contracts.length }}</span>
            </div>
            @if (client()!.contracts.length === 0) {
              <p class="text-sm text-gray-400 py-4 text-center">Sin contratos registrados</p>
            } @else {
              <div class="overflow-x-auto">
                <table class="w-full text-sm">
                  <thead>
                    <tr class="text-xs text-gray-400 border-b border-gray-100">
                      <th class="text-left pb-2 font-medium">Vehículo</th>
                      <th class="text-left pb-2 font-medium">Inicio</th>
                      <th class="text-left pb-2 font-medium">Fin</th>
                      <th class="text-left pb-2 font-medium">Estado</th>
                      <th class="text-right pb-2 font-medium">Precio</th>
                      <th class="pb-2"></th>
                    </tr>
                  </thead>
                  <tbody>
                    @for (c of client()!.contracts; track c.id) {
                      <tr class="border-b border-gray-50 last:border-0">
                        <td class="py-2.5 pr-3">
                          <p class="font-medium text-gray-900">{{ c.car.brand }} {{ c.car.model }}</p>
                          <p class="text-xs font-mono text-gray-400">{{ c.car.licensePlate }}</p>
                        </td>
                        <td class="py-2.5 pr-3 text-gray-600">{{ c.startDate | date:'dd/MM/yy' }}</td>
                        <td class="py-2.5 pr-3 text-gray-600">{{ c.endDate | date:'dd/MM/yy' }}</td>
                        <td class="py-2.5 pr-3">
                          <app-contract-badge [status]="c.status"></app-contract-badge>
                        </td>
                        <td class="py-2.5 pr-3 text-right font-medium text-gray-900">{{ c.totalPrice | number:'1.2-2' }} €</td>
                        <td class="py-2.5 text-right">
                          <a [routerLink]="['/rentals', c.id]" class="text-xs text-blue-500 hover:underline">Ver</a>
                        </td>
                      </tr>
                    }
                  </tbody>
                </table>
              </div>
            }
          </div>

          <!-- Incidencias -->
          <div class="card p-5">
            <div class="flex items-center gap-2 mb-4">
              <lucide-icon [img]="AlertTriangle" [size]="15" class="text-gray-400"></lucide-icon>
              <h3 class="text-sm font-semibold text-gray-700">Incidencias</h3>
              <span class="ml-auto text-xs text-gray-400">{{ client()!.incidents.length }}</span>
            </div>
            @if (client()!.incidents.length === 0) {
              <p class="text-sm text-gray-400 py-4 text-center">Sin incidencias registradas</p>
            } @else {
              <div class="space-y-2">
                @for (inc of client()!.incidents; track inc.id) {
                  <div class="border border-gray-100 rounded-xl p-3">
                    <div class="flex items-start justify-between gap-2 flex-wrap">
                      <div class="flex items-center gap-2 flex-wrap">
                        <app-incident-type-badge [type]="inc.type"></app-incident-type-badge>
                        <app-severity-badge [severity]="inc.severity"></app-severity-badge>
                        @if (inc.resolved) {
                          <span class="text-xs text-green-600 bg-green-50 px-2 py-0.5 rounded-full">Resuelta</span>
                        }
                      </div>
                      <span class="text-xs text-gray-400">{{ inc.createdAt | date:'dd/MM/yyyy' }}</span>
                    </div>
                    <p class="text-sm text-gray-600 mt-2">{{ inc.description }}</p>
                    @if (inc.contract) {
                      <p class="text-xs text-gray-400 mt-1">
                        Contrato · {{ inc.contract.car.brand }} {{ inc.contract.car.model }}
                        <span class="font-mono">({{ inc.contract.car.licensePlate }})</span>
                      </p>
                    }
                  </div>
                }
              </div>
            }
          </div>

        </div>
      </div>
    }
  `,
})
export class ClientDetailComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private clientsService = inject(ClientsService);

  readonly ArrowLeft = ArrowLeft;
  readonly User = User;
  readonly Car = Car;
  readonly FileText = FileText;
  readonly AlertTriangle = AlertTriangle;
  readonly MapPin = MapPin;
  readonly Phone = Phone;
  readonly Mail = Mail;
  readonly CreditCard = CreditCard;

  loading = signal(true);
  client = signal<ClientDetail | null>(null);

  ngOnInit() {
    const id = +this.route.snapshot.paramMap.get('id')!;
    this.clientsService.getById(id).subscribe({
      next: data => { this.client.set(data as unknown as ClientDetail); this.loading.set(false); },
      error: () => this.loading.set(false),
    });
  }
}
