// frontend/src/app/features/clients/client-list.component.ts
import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { FormBuilder, Validators, ReactiveFormsModule } from '@angular/forms';
import { LucideAngularModule, Plus, Pencil, Trash2, ShieldAlert, ShieldOff, Users, Search } from 'lucide-angular';
import { ClientsService } from '../../core/services/clients.service';
import { SpinnerComponent } from '../../shared/components/spinner.component';
import { PageHeaderComponent } from '../../shared/components/page-header.component';
import { ButtonComponent } from '../../shared/components/button.component';
import { BlacklistedBadgeComponent } from '../../shared/components/badge.component';
import type { Client } from '../../core/models';

@Component({
  selector: 'app-client-list',
  standalone: true,
  imports: [ReactiveFormsModule, LucideAngularModule, SpinnerComponent, PageHeaderComponent, ButtonComponent, BlacklistedBadgeComponent],
  template: `
    <app-page-header title="Clientes" [subtitle]="clients().length + ' registros'">
      <app-button (clicked)="openCreate()">
        <lucide-icon [img]="Plus" [size]="14"></lucide-icon>
        Nuevo cliente
      </app-button>
    </app-page-header>

    <div class="flex items-center gap-3 mb-5">
      <div class="relative flex-1 max-w-xs">
        <lucide-icon [img]="Search" [size]="14" class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none"></lucide-icon>
        <input [value]="search()" (input)="search.set($any($event.target).value)"
               class="form-input pl-9" placeholder="Buscar por nombre, DNI...">
      </div>
      <button [class]="'filter-tab ' + (filter() === 'all' ? 'filter-tab-active' : 'filter-tab-inactive')" (click)="filter.set('all')">Todos</button>
      <button [class]="'filter-tab ' + (filter() === 'blacklisted' ? 'filter-tab-active' : 'filter-tab-inactive')" (click)="filter.set('blacklisted')">Lista negra</button>
    </div>

    @if (loading()) {
      <app-spinner></app-spinner>
    } @else {
      <div class="card overflow-hidden">
        <table class="data-table">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>DNI</th>
              <th>Email</th>
              <th>Teléfono</th>
              <th>Estado</th>
              <th>Incidencias</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            @for (c of filtered(); track c.id) {
              <tr>
                <td class="font-medium text-gray-900">{{ c.name }}</td>
                <td class="font-mono text-sm text-gray-600">{{ c.dni }}</td>
                <td class="text-gray-500">{{ c.email }}</td>
                <td class="text-gray-500">{{ c.phone }}</td>
                <td>
                  @if (c.isBlacklisted) {
                    <app-blacklisted-badge></app-blacklisted-badge>
                  } @else {
                    <span class="text-xs text-gray-400">Normal</span>
                  }
                </td>
                <td><span class="text-sm text-gray-600">{{ c._count?.incidents ?? 0 }}</span></td>
                <td class="space-x-0.5">
                  <button (click)="toggleBlacklist(c)" title="{{ c.isBlacklisted ? 'Quitar de lista negra' : 'Añadir a lista negra' }}"
                          class="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-gray-700 transition-colors">
                    <lucide-icon [img]="c.isBlacklisted ? ShieldOff : ShieldAlert" [size]="14"></lucide-icon>
                  </button>
                  <button (click)="openEdit(c)" class="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-gray-700 transition-colors">
                    <lucide-icon [img]="Pencil" [size]="14"></lucide-icon>
                  </button>
                  <button (click)="confirmDelete(c.id)" class="p-1.5 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-500 transition-colors">
                    <lucide-icon [img]="Trash2" [size]="14"></lucide-icon>
                  </button>
                </td>
              </tr>
            } @empty {
              <tr>
                <td colspan="7" class="text-center py-14 text-gray-400">
                  <lucide-icon [img]="Users" [size]="32" class="mx-auto mb-2 opacity-20"></lucide-icon>
                  <p class="text-sm">No hay clientes</p>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }

    @if (showModal()) {
      <div class="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
        <div class="bg-white rounded-2xl w-full max-w-lg shadow-2xl">
          <div class="px-6 py-4 border-b border-gray-100">
            <h2 class="text-base font-semibold text-gray-900">{{ editingId() ? 'Editar cliente' : 'Nuevo cliente' }}</h2>
          </div>
          <form [formGroup]="form" (ngSubmit)="save()" class="p-6">
            <div class="grid grid-cols-2 gap-4">
              <div class="col-span-2">
                <label class="form-label">Nombre completo *</label>
                <input formControlName="name" class="form-input" placeholder="Juan García López">
              </div>
              <div>
                <label class="form-label">DNI / NIE *</label>
                <input formControlName="dni" class="form-input" placeholder="12345678A">
              </div>
              <div>
                <label class="form-label">Teléfono *</label>
                <input formControlName="phone" class="form-input" placeholder="600 000 000">
              </div>
              <div class="col-span-2">
                <label class="form-label">Email *</label>
                <input formControlName="email" type="email" class="form-input" placeholder="juan@email.com">
              </div>
              <div class="col-span-2">
                <label class="form-label">Dirección</label>
                <input formControlName="address" class="form-input" placeholder="Calle Principal 1, Madrid">
              </div>
              <div class="col-span-2">
                <label class="form-label">Notas</label>
                <textarea formControlName="notes" class="form-textarea" rows="2" placeholder="Observaciones..."></textarea>
              </div>
              <div class="col-span-2 flex items-center gap-2">
                <input formControlName="isBlacklisted" type="checkbox" id="cb-blacklisted" class="w-4 h-4 rounded border-gray-300 accent-gray-900">
                <label for="cb-blacklisted" class="text-sm text-gray-700 cursor-pointer">En lista negra</label>
              </div>
            </div>
            <div class="flex justify-end gap-3 mt-6 pt-4 border-t border-gray-100">
              <app-button variant="secondary" (clicked)="closeModal()">Cancelar</app-button>
              <app-button type="submit" [loading]="saving()">Guardar</app-button>
            </div>
          </form>
        </div>
      </div>
    }

    @if (deleteId()) {
      <div class="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
        <div class="bg-white rounded-2xl w-full max-w-sm shadow-2xl p-6">
          <h2 class="text-base font-semibold text-gray-900 mb-1">¿Eliminar cliente?</h2>
          <p class="text-sm text-gray-500 mb-6">Esta acción no se puede deshacer.</p>
          <div class="flex justify-end gap-3">
            <app-button variant="secondary" (clicked)="deleteId.set(null)">Cancelar</app-button>
            <app-button variant="danger" [loading]="deleting()" (clicked)="doDelete()">Eliminar</app-button>
          </div>
        </div>
      </div>
    }
  `,
})
export class ClientListComponent implements OnInit {
  private clientsService = inject(ClientsService);
  private fb = inject(FormBuilder);

  readonly Plus = Plus;
  readonly Pencil = Pencil;
  readonly Trash2 = Trash2;
  readonly ShieldAlert = ShieldAlert;
  readonly ShieldOff = ShieldOff;
  readonly Users = Users;
  readonly Search = Search;

  loading = signal(true);
  saving = signal(false);
  deleting = signal(false);
  clients = signal<Client[]>([]);
  search = signal('');
  filter = signal<'all' | 'blacklisted'>('all');
  showModal = signal(false);
  editingId = signal<number | null>(null);
  deleteId = signal<number | null>(null);

  form = this.fb.group({
    name: ['', Validators.required],
    dni: ['', Validators.required],
    email: ['', [Validators.required, Validators.email]],
    phone: ['', Validators.required],
    address: [''],
    notes: [''],
    isBlacklisted: [false],
  });

  filtered = computed(() => {
    const q = this.search().toLowerCase();
    return this.clients().filter(c => {
      const matchSearch = !q || c.name.toLowerCase().includes(q) || c.dni.toLowerCase().includes(q) || c.email.toLowerCase().includes(q);
      const matchFilter = this.filter() === 'all' || (this.filter() === 'blacklisted' && c.isBlacklisted);
      return matchSearch && matchFilter;
    });
  });

  ngOnInit() { this.load(); }

  load() {
    this.clientsService.getAll().subscribe({
      next: data => { this.clients.set(data); this.loading.set(false); },
      error: () => this.loading.set(false),
    });
  }

  openCreate() {
    this.editingId.set(null);
    this.form.reset({ isBlacklisted: false });
    this.showModal.set(true);
  }

  openEdit(c: Client) {
    this.editingId.set(c.id);
    this.form.patchValue(c);
    this.showModal.set(true);
  }

  closeModal() { this.showModal.set(false); }

  save() {
    if (this.form.invalid) return;
    this.saving.set(true);
    const data = this.form.value as Partial<Client>;
    const op = this.editingId()
      ? this.clientsService.update(this.editingId()!, data)
      : this.clientsService.create(data);
    op.subscribe({
      next: () => { this.saving.set(false); this.closeModal(); this.load(); },
      error: () => this.saving.set(false),
    });
  }

  confirmDelete(id: number) { this.deleteId.set(id); }

  doDelete() {
    if (!this.deleteId()) return;
    this.deleting.set(true);
    this.clientsService.delete(this.deleteId()!).subscribe({
      next: () => { this.deleting.set(false); this.deleteId.set(null); this.load(); },
      error: () => this.deleting.set(false),
    });
  }

  toggleBlacklist(c: Client) {
    this.clientsService.update(c.id, { isBlacklisted: !c.isBlacklisted }).subscribe({
      next: () => this.clients.update(list => list.map(x => x.id === c.id ? { ...x, isBlacklisted: !x.isBlacklisted } : x)),
    });
  }
}

// frontend/src/pages/clients/ClientList.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Users, Plus, Search, Trash2, Eye, ShieldAlert } from 'lucide-react';
import { clientsApi } from '../../api/clients';
import PageHeader from '../../components/ui/PageHeader';
import Spinner from '../../components/ui/Spinner';
import EmptyState from '../../components/ui/EmptyState';
import Button from '../../components/ui/Button';

export default function ClientList() {
  const [search, setSearch] = useState('');
  const [filterBlacklisted, setFilterBlacklisted] = useState<boolean | undefined>(undefined);
  const qc = useQueryClient();

  const { data: clients, isPending } = useQuery({
    queryKey: ['clients', filterBlacklisted],
    queryFn: () =>
      clientsApi
        .getAll(filterBlacklisted !== undefined ? { blacklisted: filterBlacklisted } : undefined)
        .then((r) => r.data),
  });

  const deleteMutation = useMutation({
    mutationFn: clientsApi.delete,
    onSuccess: () => qc.invalidateQueries({ queryKey: ['clients'] }),
  });

  const filtered = (clients ?? []).filter(
    (c) =>
      c.name.toLowerCase().includes(search.toLowerCase()) ||
      c.dni.toLowerCase().includes(search.toLowerCase()) ||
      c.email.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="p-8">
      <PageHeader
        title="Clientes"
        subtitle={`${clients?.length ?? 0} clientes registrados`}
        action={
          <Link to="/clients/new">
            <Button>
              <Plus size={16} />
              Nuevo cliente
            </Button>
          </Link>
        }
      />

      {/* Filters */}
      <div className="flex gap-3 mb-6">
        <div className="relative flex-1 max-w-sm">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
          <input
            type="text"
            placeholder="Buscar por nombre, DNI o email…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="form-input pl-9"
          />
        </div>
        <select
          value={filterBlacklisted === undefined ? '' : String(filterBlacklisted)}
          onChange={(e) =>
            setFilterBlacklisted(e.target.value === '' ? undefined : e.target.value === 'true')
          }
          className="form-select w-44"
        >
          <option value="">Todos</option>
          <option value="false">Sin restricciones</option>
          <option value="true">Lista negra</option>
        </select>
      </div>

      {/* Table */}
      <div className="card overflow-hidden">
        {isPending ? (
          <Spinner />
        ) : filtered.length === 0 ? (
          <EmptyState icon={Users} title="Sin clientes" description="Añade tu primer cliente para empezar." />
        ) : (
          <table className="data-table w-full text-sm">
            <thead>
              <tr className="border-b border-gray-100 bg-gray-50/60">
                <th className="text-left px-6 py-3 text-xs font-semibold text-gray-400 uppercase tracking-wide">Nombre</th>
                <th className="text-left px-6 py-3 text-xs font-semibold text-gray-400 uppercase tracking-wide">DNI</th>
                <th className="text-left px-6 py-3 text-xs font-semibold text-gray-400 uppercase tracking-wide">Teléfono</th>
                <th className="text-left px-6 py-3 text-xs font-semibold text-gray-400 uppercase tracking-wide">Contratos</th>
                <th className="text-left px-6 py-3 text-xs font-semibold text-gray-400 uppercase tracking-wide">Estado</th>
                <th className="px-6 py-3"></th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((client) => (
                <tr
                  key={client.id}
                  className={`border-b border-gray-50 last:border-0 transition-colors ${
                    client.isBlacklisted
                      ? 'bg-gray-900 hover:bg-gray-800'
                      : 'hover:bg-gray-50'
                  }`}
                >
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-semibold ${
                        client.isBlacklisted ? 'bg-gray-700 text-white' : 'bg-gray-100 text-gray-700'
                      }`}>
                        {client.name.charAt(0).toUpperCase()}
                      </div>
                      <div>
                        <p className={`font-medium ${client.isBlacklisted ? 'text-white' : 'text-gray-900'}`}>
                          {client.name}
                        </p>
                        <p className={`text-xs ${client.isBlacklisted ? 'text-gray-400' : 'text-gray-400'}`}>
                          {client.email}
                        </p>
                      </div>
                    </div>
                  </td>
                  <td className={`px-6 py-4 font-mono text-sm ${client.isBlacklisted ? 'text-gray-300' : 'text-gray-600'}`}>
                    {client.dni}
                  </td>
                  <td className={`px-6 py-4 ${client.isBlacklisted ? 'text-gray-300' : 'text-gray-600'}`}>
                    {client.phone}
                  </td>
                  <td className={`px-6 py-4 ${client.isBlacklisted ? 'text-gray-300' : 'text-gray-600'}`}>
                    {client._count?.contracts ?? 0}
                  </td>
                  <td className="px-6 py-4">
                    {client.isBlacklisted ? (
                      <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-white text-gray-900">
                        <ShieldAlert size={11} /> Lista negra
                      </span>
                    ) : (
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-500">
                        OK
                      </span>
                    )}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2 justify-end">
                      <Link to={`/clients/${client.id}`}>
                        <Button
                          variant="ghost"
                          size="sm"
                          className={client.isBlacklisted ? 'text-gray-300 hover:bg-gray-700 hover:text-white' : ''}
                        >
                          <Eye size={14} />
                        </Button>
                      </Link>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => {
                          if (confirm('¿Eliminar este cliente?')) {
                            deleteMutation.mutate(client.id);
                          }
                        }}
                        className={client.isBlacklisted ? 'text-gray-500 hover:bg-gray-700 hover:text-white' : 'text-gray-400 hover:text-gray-700'}
                      >
                        <Trash2 size={14} />
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
