// frontend/src/app/features/repairs/repair-list.component.ts
import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { FormBuilder, Validators, ReactiveFormsModule } from '@angular/forms';
import { DatePipe, DecimalPipe } from '@angular/common';
import { LucideAngularModule, Plus, Pencil, Trash2, Hammer, Search } from 'lucide-angular';
import { RepairsService } from '../../core/services/repairs.service';
import { CarsService } from '../../core/services/cars.service';
import { SpinnerComponent } from '../../shared/components/spinner.component';
import { PageHeaderComponent } from '../../shared/components/page-header.component';
import { ButtonComponent } from '../../shared/components/button.component';
import { RepairBadgeComponent } from '../../shared/components/badge.component';
import type { Repair, Car, RepairStatus } from '../../core/models';

@Component({
  selector: 'app-repair-list',
  standalone: true,
  imports: [ReactiveFormsModule, DatePipe, DecimalPipe, LucideAngularModule, SpinnerComponent, PageHeaderComponent, ButtonComponent, RepairBadgeComponent],
  template: `
    <app-page-header title="Reparaciones" [subtitle]="repairs().length + ' reparaciones'">
      <app-button (clicked)="openCreate()">
        <lucide-icon [img]="Plus" [size]="14"></lucide-icon>
        Nueva reparación
      </app-button>
    </app-page-header>

    <div class="flex items-center gap-3 mb-5 flex-wrap">
      <div class="relative flex-1 max-w-xs">
        <lucide-icon [img]="Search" [size]="14" class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none"></lucide-icon>
        <input [value]="search()" (input)="search.set($any($event.target).value)"
               class="form-input pl-9" placeholder="Buscar por matrícula...">
      </div>
      @for (s of statuses; track s.value) {
        <button [class]="'filter-tab ' + (statusFilter() === s.value ? 'filter-tab-active' : 'filter-tab-inactive')"
                (click)="statusFilter.set(s.value)">{{ s.label }}</button>
      }
    </div>

    @if (loading()) {
      <app-spinner></app-spinner>
    } @else {
      <div class="card overflow-hidden">
        <table class="data-table">
          <thead>
            <tr>
              <th>Vehículo</th>
              <th>Descripción</th>
              <th>Estado</th>
              <th>Coste</th>
              <th>Inicio</th>
              <th>Fin</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            @for (r of filtered(); track r.id) {
              <tr>
                <td>
                  <p class="font-mono font-medium text-gray-900">{{ r.car.licensePlate }}</p>
                  <p class="text-xs text-gray-400">{{ r.car.brand }} {{ r.car.model }}</p>
                </td>
                <td class="text-sm text-gray-600 max-w-xs truncate">{{ r.description }}</td>
                <td><app-repair-badge [status]="r.status"></app-repair-badge></td>
                <td class="text-gray-700">{{ r.cost != null ? (r.cost | number:'1.2-2') + ' €' : '—' }}</td>
                <td class="text-sm text-gray-500">{{ r.startDate ? (r.startDate | date:'dd/MM/yyyy') : '—' }}</td>
                <td class="text-sm text-gray-500">{{ r.endDate ? (r.endDate | date:'dd/MM/yyyy') : '—' }}</td>
                <td class="space-x-0.5">
                  <button (click)="openEdit(r)" class="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-gray-700 transition-colors">
                    <lucide-icon [img]="Pencil" [size]="14"></lucide-icon>
                  </button>
                  <button (click)="confirmDelete(r.id)" class="p-1.5 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-500 transition-colors">
                    <lucide-icon [img]="Trash2" [size]="14"></lucide-icon>
                  </button>
                </td>
              </tr>
            } @empty {
              <tr>
                <td colspan="7" class="text-center py-14 text-gray-400">
                  <lucide-icon [img]="Hammer" [size]="32" class="mx-auto mb-2 opacity-20"></lucide-icon>
                  <p class="text-sm">No hay reparaciones</p>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }

    @if (showModal()) {
      <div class="modal-overlay">
        <div class="modal-inner">
          <div class="modal-dialog bg-white rounded-2xl max-w-lg shadow-2xl">
            <div class="px-6 py-4 border-b border-gray-100">
              <h2 class="text-base font-semibold text-gray-900">{{ editingId() ? 'Editar reparación' : 'Nueva reparación' }}</h2>
            </div>
            <form [formGroup]="form" (ngSubmit)="save()" class="p-6">
              <div class="grid grid-cols-2 gap-4">
                <div class="col-span-2">
                  <label class="form-label">Vehículo *</label>
                  <select formControlName="carId" class="form-select">
                    <option [ngValue]="null" disabled>Seleccionar vehículo</option>
                    @for (c of carOptions(); track c.id) {
                      <option [ngValue]="c.id">{{ c.licensePlate }} — {{ c.brand }} {{ c.model }}</option>
                    }
                  </select>
                </div>
                <div class="col-span-2">
                  <label class="form-label">Descripción *</label>
                  <textarea formControlName="description" class="form-textarea" rows="2" placeholder="Describe la reparación..."></textarea>
                </div>
                <div>
                  <label class="form-label">Estado</label>
                  <select formControlName="status" class="form-select">
                    <option value="PENDING">Pendiente</option>
                    <option value="IN_PROGRESS">En proceso</option>
                    <option value="COMPLETED">Completada</option>
                    <option value="CANCELLED">Cancelada</option>
                  </select>
                </div>
                <div>
                  <label class="form-label">Coste (€)</label>
                  <input formControlName="cost" type="number" step="0.01" class="form-input" placeholder="0.00">
                </div>
                <div>
                  <label class="form-label">Fecha inicio</label>
                  <input formControlName="startDate" type="date" class="form-input">
                </div>
                <div>
                  <label class="form-label">Fecha fin</label>
                  <input formControlName="endDate" type="date" class="form-input">
                </div>
              </div>
              <div class="flex justify-end gap-3 mt-6 pt-4 border-t border-gray-100">
                <app-button variant="secondary" (clicked)="closeModal()">Cancelar</app-button>
                <app-button type="submit" [loading]="saving()">Guardar</app-button>
              </div>
            </form>
          </div>
        </div>
      </div>
    }

    @if (deleteId()) {
      <div class="modal-overlay">
        <div class="modal-inner">
          <div class="modal-dialog bg-white rounded-2xl max-w-sm shadow-2xl p-6">
            <h2 class="text-base font-semibold text-gray-900 mb-1">¿Eliminar reparación?</h2>
            <p class="text-sm text-gray-500 mb-6">Esta acción no se puede deshacer.</p>
            <div class="flex justify-end gap-3">
              <app-button variant="secondary" (clicked)="deleteId.set(null)">Cancelar</app-button>
              <app-button variant="danger" [loading]="deleting()" (clicked)="doDelete()">Eliminar</app-button>
            </div>
          </div>
        </div>
      </div>
    }
  `,
})
export class RepairListComponent implements OnInit {
  private repairsService = inject(RepairsService);
  private carsService = inject(CarsService);
  private fb = inject(FormBuilder);

  readonly Plus = Plus;
  readonly Pencil = Pencil;
  readonly Trash2 = Trash2;
  readonly Hammer = Hammer;
  readonly Search = Search;

  statuses = [
    { value: '' as any, label: 'Todas' },
    { value: 'PENDING' as RepairStatus, label: 'Pendientes' },
    { value: 'IN_PROGRESS' as RepairStatus, label: 'En proceso' },
    { value: 'COMPLETED' as RepairStatus, label: 'Completadas' },
    { value: 'CANCELLED' as RepairStatus, label: 'Canceladas' },
  ];

  loading = signal(true);
  saving = signal(false);
  deleting = signal(false);
  repairs = signal<Repair[]>([]);
  carOptions = signal<Car[]>([]);
  search = signal('');
  statusFilter = signal<RepairStatus | ''>('');
  showModal = signal(false);
  editingId = signal<number | null>(null);
  deleteId = signal<number | null>(null);

  form = this.fb.group({
    carId: [null as number | null, Validators.required],
    description: ['', Validators.required],
    status: ['PENDING' as RepairStatus],
    cost: [null as number | null],
    startDate: [''],
    endDate: [''],
  });

  filtered = computed(() => {
    const q = this.search().toLowerCase();
    const s = this.statusFilter();
    return this.repairs().filter(r => {
      const matchSearch = !q || r.car.licensePlate.toLowerCase().includes(q) || r.description.toLowerCase().includes(q);
      const matchStatus = !s || r.status === s;
      return matchSearch && matchStatus;
    });
  });

  ngOnInit() {
    this.load();
    this.carsService.getAll().subscribe({ next: data => this.carOptions.set(data) });
  }

  load() {
    this.repairsService.getAll().subscribe({
      next: data => { this.repairs.set(data); this.loading.set(false); },
      error: () => this.loading.set(false),
    });
  }

  openCreate() {
    this.editingId.set(null);
    this.form.reset({ status: 'PENDING' });
    this.showModal.set(true);
  }

  openEdit(r: Repair) {
    this.editingId.set(r.id);
    this.form.patchValue({
      carId: r.carId,
      description: r.description,
      status: r.status,
      cost: r.cost ?? null,
      startDate: r.startDate?.split('T')[0] ?? '',
      endDate: r.endDate?.split('T')[0] ?? '',
    });
    this.showModal.set(true);
  }

  closeModal() { this.showModal.set(false); }

  save() {
    if (this.form.invalid) return;
    this.saving.set(true);
    const v = this.form.value as Partial<Repair>;
    const op = this.editingId()
      ? this.repairsService.update(this.editingId()!, v)
      : this.repairsService.create(v);
    op.subscribe({
      next: () => { this.saving.set(false); this.closeModal(); this.load(); },
      error: () => this.saving.set(false),
    });
  }

  confirmDelete(id: number) { this.deleteId.set(id); }

  doDelete() {
    if (!this.deleteId()) return;
    this.deleting.set(true);
    this.repairsService.delete(this.deleteId()!).subscribe({
      next: () => { this.deleting.set(false); this.deleteId.set(null); this.load(); },
      error: () => this.deleting.set(false),
    });
  }
}

// frontend/src/pages/repairs/RepairList.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Hammer, Plus, Trash2, Edit2 } from 'lucide-react';
import { repairsApi } from '../../api/repairs';
import PageHeader from '../../components/ui/PageHeader';
import Spinner from '../../components/ui/Spinner';
import EmptyState from '../../components/ui/EmptyState';
import Button from '../../components/ui/Button';
import { RepairBadge } from '../../components/ui/Badge';
import type { RepairStatus } from '../../types';

export default function RepairList() {
  const [statusFilter, setStatusFilter] = useState<RepairStatus | ''>('');
  const qc = useQueryClient();

  const { data: repairs, isPending } = useQuery({
    queryKey: ['repairs', statusFilter],
    queryFn: () =>
      repairsApi.getAll(statusFilter ? { status: statusFilter } : undefined).then((r) => r.data),
  });

  const deleteMutation = useMutation({
    mutationFn: repairsApi.delete,
    onSuccess: () => qc.invalidateQueries({ queryKey: ['repairs'] }),
  });

  const updateStatus = useMutation({
    mutationFn: ({ id, status }: { id: number; status: RepairStatus }) =>
      repairsApi.update(id, { status }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['repairs'] }),
  });

  return (
    <div className="p-8">
      <PageHeader
        title="Reparaciones"
        subtitle={`${repairs?.length ?? 0} reparaciones`}
        action={
          <Link to="/repairs/new">
            <Button><Plus size={16} />Nueva reparación</Button>
          </Link>
        }
      />

      <div className="flex gap-2 mb-6">
        {(['', 'PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'] as const).map((s) => (
          <button
            key={s}
            onClick={() => setStatusFilter(s)}
            className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
              statusFilter === s
                ? 'bg-blue-600 text-white'
                : 'bg-white border border-gray-200 text-gray-600 hover:bg-gray-50'
            }`}
          >
            {s === '' ? 'Todas' : s === 'PENDING' ? 'Pendientes' : s === 'IN_PROGRESS' ? 'En proceso' : s === 'COMPLETED' ? 'Completadas' : 'Canceladas'}
          </button>
        ))}
      </div>

      <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
        {isPending ? (
          <Spinner />
        ) : !repairs?.length ? (
          <EmptyState icon={Hammer} title="Sin reparaciones" description="Registra la primera reparación." />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100">
                  <th className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">Vehículo</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">Descripción</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">Estado</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">Inicio</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">Coste</th>
                  <th className="px-6 py-3"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {repairs.map((r) => (
                  <tr key={r.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4">
                      <Link to={`/cars/${r.car.id}`} className="font-medium text-gray-700 hover:underline">
                        {r.car.brand} {r.car.model}
                      </Link>
                      <p className="text-xs text-gray-400 font-mono">{r.car.licensePlate}</p>
                    </td>
                    <td className="px-6 py-4 text-gray-900 max-w-xs">{r.description}</td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <RepairBadge status={r.status} />
                        {r.status === 'PENDING' && (
                          <button
                            onClick={() => updateStatus.mutate({ id: r.id, status: 'IN_PROGRESS' })}
                            className="text-xs text-gray-500 hover:text-gray-900"
                          >
                            Iniciar
                          </button>
                        )}
                        {r.status === 'IN_PROGRESS' && (
                          <button
                            onClick={() => updateStatus.mutate({ id: r.id, status: 'COMPLETED' })}
                            className="text-xs text-green-600 hover:underline"
                          >
                            Completar
                          </button>
                        )}
                      </div>
                    </td>
                    <td className="px-6 py-4 text-gray-600">
                      {r.startDate ? new Date(r.startDate).toLocaleDateString('es-ES') : '—'}
                    </td>
                    <td className="px-6 py-4 text-gray-600">
                      {r.cost != null ? `${r.cost.toFixed(2)} €` : '—'}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-1 justify-end">
                        <Link to={`/repairs/${r.id}/edit`}>
                          <Button variant="ghost" size="sm"><Edit2 size={14} /></Button>
                        </Link>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="text-red-500 hover:bg-red-50"
                          onClick={() => confirm('¿Eliminar?') && deleteMutation.mutate(r.id)}
                        >
                          <Trash2 size={14} />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
