// frontend/src/pages/cars/CarList.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Car, Plus, Search, Trash2, Eye } from 'lucide-react';
import { carsApi } from '../../api/cars';
import PageHeader from '../../components/ui/PageHeader';
import Spinner from '../../components/ui/Spinner';
import EmptyState from '../../components/ui/EmptyState';
import Button from '../../components/ui/Button';

export default function CarList() {
  const [search, setSearch] = useState('');
  const qc = useQueryClient();

  const { data: cars, isPending } = useQuery({
    queryKey: ['cars'],
    queryFn: () => carsApi.getAll().then((r) => r.data),
  });

  const deleteMutation = useMutation({
    mutationFn: carsApi.delete,
    onSuccess: () => qc.invalidateQueries({ queryKey: ['cars'] }),
  });

  const filtered = (cars ?? []).filter(
    (c) =>
      c.licensePlate.toLowerCase().includes(search.toLowerCase()) ||
      c.brand.toLowerCase().includes(search.toLowerCase()) ||
      c.model.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="p-8">
      <PageHeader
        title="Vehículos"
        subtitle={`${cars?.length ?? 0} vehículos registrados`}
        action={
          <Link to="/cars/new">
            <Button>
              <Plus size={16} />
              Nuevo vehículo
            </Button>
          </Link>
        }
      />

      <div className="relative max-w-sm mb-6">
        <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
        <input
          type="text"
          placeholder="Buscar por matrícula, marca o modelo…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="form-input pl-9"
        />
      </div>

      <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
        {isPending ? (
          <Spinner />
        ) : filtered.length === 0 ? (
          <EmptyState icon={Car} title="Sin vehículos" description="Añade el primer vehículo." />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100">
                  <th className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">Matrícula</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">Vehículo</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">Año</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">Color</th>
                  <th className="text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase">Cliente</th>
                  <th className="px-6 py-3"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {filtered.map((car) => (
                  <tr key={car.id} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4 font-mono font-semibold text-gray-900">{car.licensePlate}</td>
                    <td className="px-6 py-4">
                      <p className="font-medium text-gray-900">{car.brand} {car.model}</p>
                    </td>
                    <td className="px-6 py-4 text-gray-600">{car.year}</td>
                    <td className="px-6 py-4 text-gray-600">{car.color ?? '—'}</td>
                    <td className="px-6 py-4">
                      {car.client ? (
                        <Link to={`/clients/${car.client.id}`} className="text-gray-700 hover:underline">
                          {car.client.name}
                        </Link>
                      ) : (
                        <span className="text-gray-400">—</span>
                      )}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2 justify-end">
                        <Link to={`/cars/${car.id}`}>
                          <Button variant="ghost" size="sm"><Eye size={14} /></Button>
                        </Link>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="text-red-500 hover:bg-red-50"
                          onClick={() => confirm('¿Eliminar este vehículo?') && deleteMutation.mutate(car.id)}
                        >
                          <Trash2 size={14} />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

// frontend/src/app/features/cars/car-list.component.ts
import { Component, inject, signal, computed, OnInit } from '@angular/core';
import { FormBuilder, Validators, ReactiveFormsModule } from '@angular/forms';
import { LucideAngularModule, Plus, Pencil, Trash2, Car, Search } from 'lucide-angular';
import { CarsService } from '../../core/services/cars.service';
import { ClientsService } from '../../core/services/clients.service';
import { SpinnerComponent } from '../../shared/components/spinner.component';
import { PageHeaderComponent } from '../../shared/components/page-header.component';
import { ButtonComponent } from '../../shared/components/button.component';
import type { Car as CarModel, Client } from '../../core/models';

@Component({
  selector: 'app-car-list',
  standalone: true,
  imports: [ReactiveFormsModule, LucideAngularModule, SpinnerComponent, PageHeaderComponent, ButtonComponent],
  template: `
    <app-page-header title="Vehículos" [subtitle]="cars().length + ' vehículos'">
      <app-button (clicked)="openCreate()">
        <lucide-icon [img]="Plus" [size]="14"></lucide-icon>
        Nuevo vehículo
      </app-button>
    </app-page-header>

    <div class="flex items-center gap-3 mb-5">
      <div class="relative flex-1 max-w-xs">
        <lucide-icon [img]="Search" [size]="14" class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none"></lucide-icon>
        <input [value]="search()" (input)="search.set($any($event.target).value)"
               class="form-input pl-9" placeholder="Buscar por matrícula, marca...">
      </div>
    </div>

    @if (loading()) {
      <app-spinner></app-spinner>
    } @else {
      <div class="card overflow-hidden">
        <table class="data-table">
          <thead>
            <tr>
              <th>Matrícula</th>
              <th>Marca</th>
              <th>Modelo</th>
              <th>Año</th>
              <th>Color</th>
              <th>Propietario</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            @for (c of filtered(); track c.id) {
              <tr>
                <td class="font-mono font-medium text-gray-900">{{ c.licensePlate }}</td>
                <td class="text-gray-700">{{ c.brand }}</td>
                <td class="text-gray-700">{{ c.model }}</td>
                <td class="text-gray-500">{{ c.year }}</td>
                <td class="text-gray-500">{{ c.color || '—' }}</td>
                <td class="text-gray-500">{{ c.client?.name || '—' }}</td>
                <td class="space-x-0.5">
                  <button (click)="openEdit(c)" class="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-gray-700 transition-colors">
                    <lucide-icon [img]="Pencil" [size]="14"></lucide-icon>
                  </button>
                  <button (click)="confirmDelete(c.id)" class="p-1.5 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-500 transition-colors">
                    <lucide-icon [img]="Trash2" [size]="14"></lucide-icon>
                  </button>
                </td>
              </tr>
            } @empty {
              <tr>
                <td colspan="7" class="text-center py-14 text-gray-400">
                  <lucide-icon [img]="Car" [size]="32" class="mx-auto mb-2 opacity-20"></lucide-icon>
                  <p class="text-sm">No hay vehículos</p>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }

    @if (showModal()) {
      <div class="modal-overlay">
        <div class="modal-inner">
          <div class="modal-dialog bg-white rounded-2xl max-w-lg shadow-2xl">
            <div class="px-6 py-4 border-b border-gray-100">
              <h2 class="text-base font-semibold text-gray-900">{{ editingId() ? 'Editar vehículo' : 'Nuevo vehículo' }}</h2>
            </div>
            <form [formGroup]="form" (ngSubmit)="save()" class="p-6">
              <div class="grid grid-cols-2 gap-4">
                <div class="col-span-2">
                  <label class="form-label">Matrícula *</label>
                  <input formControlName="licensePlate" class="form-input font-mono uppercase" maxlength="8" placeholder="0000 AAA">
                </div>
                <div>
                  <label class="form-label">Marca *</label>
                  <input formControlName="brand" class="form-input" maxlength="50" placeholder="Toyota">
                </div>
                <div>
                  <label class="form-label">Modelo *</label>
                  <input formControlName="model" class="form-input" maxlength="50" placeholder="Corolla">
                </div>
                <div>
                  <label class="form-label">Año *</label>
                  <input formControlName="year" type="number" min="1900" [max]="maxVehicleYear" class="form-input" placeholder="2020">
                </div>
                <div>
                  <label class="form-label">Color</label>
                  <input formControlName="color" class="form-input" maxlength="30" placeholder="Blanco">
                </div>
                <div class="col-span-2">
                  <label class="form-label">Propietario</label>
                  <select formControlName="clientId" class="form-select">
                    <option [ngValue]="null">Sin propietario</option>
                    @for (client of clients(); track client.id) {
                      <option [ngValue]="client.id">{{ client.name }} — {{ client.dni }}</option>
                    }
                  </select>
                </div>
              </div>
              <div class="flex justify-end gap-3 mt-6 pt-4 border-t border-gray-100">
                <app-button variant="secondary" (clicked)="closeModal()">Cancelar</app-button>
                <app-button type="submit" [loading]="saving()">Guardar</app-button>
              </div>
            </form>
          </div>
        </div>
      </div>
    }

    @if (deleteId()) {
      <div class="modal-overlay">
        <div class="modal-inner">
          <div class="modal-dialog bg-white rounded-2xl max-w-sm shadow-2xl p-6">
            <h2 class="text-base font-semibold text-gray-900 mb-1">¿Eliminar vehículo?</h2>
            <p class="text-sm text-gray-500 mb-6">Esta acción no se puede deshacer.</p>
            <div class="flex justify-end gap-3">
              <app-button variant="secondary" (clicked)="deleteId.set(null)">Cancelar</app-button>
              <app-button variant="danger" [loading]="deleting()" (clicked)="doDelete()">Eliminar</app-button>
            </div>
          </div>
        </div>
      </div>
    }
  `,
})
export class CarListComponent implements OnInit {
  private carsService = inject(CarsService);
  private clientsService = inject(ClientsService);
  private fb = inject(FormBuilder);

  readonly Plus = Plus;
  readonly Pencil = Pencil;
  readonly Trash2 = Trash2;
  readonly Car = Car;
  readonly Search = Search;
  readonly maxVehicleYear = new Date().getFullYear() + 1;

  loading = signal(true);
  saving = signal(false);
  deleting = signal(false);
  cars = signal<CarModel[]>([]);
  clients = signal<Client[]>([]);
  search = signal('');
  showModal = signal(false);
  editingId = signal<number | null>(null);
  deleteId = signal<number | null>(null);

  form = this.fb.group({
    licensePlate: ['', [Validators.required, Validators.pattern(/^\d{4}\s?[A-Za-z]{3}$/)]],
    brand: ['', [Validators.required, Validators.maxLength(50), Validators.pattern(/^.*\S.*$/)]],
    model: ['', [Validators.required, Validators.maxLength(50), Validators.pattern(/^.*\S.*$/)]],
    year: [new Date().getFullYear(), [Validators.required, Validators.min(1900), Validators.max(this.maxVehicleYear)]],
    color: ['', Validators.maxLength(30)],
    clientId: [null as number | null],
  });

  filtered = computed(() => {
    const q = this.search().toLowerCase();
    return this.cars().filter(c =>
      !q || c.licensePlate.toLowerCase().includes(q) || c.brand.toLowerCase().includes(q) || c.model.toLowerCase().includes(q)
    );
  });

  ngOnInit() {
    this.load();
    this.clientsService.getAll().subscribe({ next: data => this.clients.set(data) });
  }

  load() {
    this.carsService.getAll().subscribe({
      next: data => { this.cars.set(data); this.loading.set(false); },
      error: () => this.loading.set(false),
    });
  }

  openCreate() {
    this.editingId.set(null);
    this.form.reset({ year: new Date().getFullYear(), clientId: null });
    this.showModal.set(true);
  }

  openEdit(c: CarModel) {
    this.editingId.set(c.id);
    this.form.patchValue({ ...c, clientId: c.clientId ?? null });
    this.showModal.set(true);
  }

  closeModal() { this.showModal.set(false); }

  save() {
    if (this.form.invalid) {
      Object.values(this.form.controls).forEach(control => {
        if (control.invalid) {
          control.markAsTouched();
          control.markAsDirty();
        }
      });
      return;
    }
    this.saving.set(true);
    const v = this.form.value;
    const data: Omit<Partial<CarModel>, 'clientId'> & { clientId?: number | null } = {
      licensePlate: v.licensePlate!.replace(/\s/g, '').toUpperCase(),
      brand: v.brand!.trim(),
      model: v.model!.trim(),
      year: v.year!,
      color: v.color?.trim() || undefined,
      clientId: v.clientId ?? null,
    };
    const op = this.editingId()
      ? this.carsService.update(this.editingId()!, data)
      : this.carsService.create(data);
    op.subscribe({
      next: () => { this.saving.set(false); this.closeModal(); this.load(); },
      error: () => this.saving.set(false),
    });
  }

  confirmDelete(id: number) { this.deleteId.set(id); }

  doDelete() {
    if (!this.deleteId()) return;
    this.deleting.set(true);
    this.carsService.delete(this.deleteId()!).subscribe({
      next: () => { this.deleting.set(false); this.deleteId.set(null); this.load(); },
      error: () => this.deleting.set(false),
    });
  }
}
