// frontend/src/app/features/login/login.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { LucideAngularModule, ShieldAlert, LogIn } from 'lucide-angular';
import { AuthService } from '../../core/services/auth.service';
import { ButtonComponent } from '../../shared/components/button.component';
import type { Employee } from '../../core/models';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, LucideAngularModule, ButtonComponent],
  template: `
    <div class="min-h-screen bg-gray-50 flex items-center justify-center p-4">
      <div class="w-full max-w-sm">
        <div class="flex flex-col items-center mb-8">
          <div class="w-12 h-12 bg-gray-900 rounded-2xl flex items-center justify-center mb-4">
            <lucide-icon [img]="ShieldAlert" [size]="22" class="text-white"></lucide-icon>
          </div>
          <h1 class="text-xl font-semibold text-gray-900">BlackList</h1>
          <p class="text-sm text-gray-400 mt-1">Inicia sesión en tu cuenta</p>
        </div>
        <div class="card p-6">
          <form [formGroup]="form" (ngSubmit)="submit()">
            <div class="space-y-4">
              <div>
                <label class="form-label">Correo electrónico</label>
                <input formControlName="email" type="email" class="form-input" placeholder="nombre@empresa.com">
              </div>
              <div>
                <label class="form-label">Contraseña</label>
                <input formControlName="password" type="password" class="form-input" placeholder="••••••••">
              </div>
              @if (error()) {
                <p class="text-sm text-red-600 bg-red-50 px-3 py-2 rounded-lg">{{ error() }}</p>
              }
              <app-button type="submit" [loading]="loading()" extraClass="w-full justify-center">
                <lucide-icon [img]="LogIn" [size]="14"></lucide-icon>
                Iniciar sesión
              </app-button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `,
})
export class LoginComponent {
  private fb = inject(FormBuilder);
  private http = inject(HttpClient);
  private auth = inject(AuthService);
  private router = inject(Router);

  readonly ShieldAlert = ShieldAlert;
  readonly LogIn = LogIn;

  loading = signal(false);
  error = signal('');

  form = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', Validators.required],
  });

  submit() {
    if (this.form.invalid) return;
    this.loading.set(true);
    this.error.set('');
    this.http.post<{ token: string; employee: Employee }>('/api/auth/login', this.form.value).subscribe({
      next: ({ token, employee }) => {
        this.auth.login(token, employee);
        this.router.navigate(['/']);
      },
      error: () => {
        this.error.set('Credenciales incorrectas. Inténtalo de nuevo.');
        this.loading.set(false);
      },
    });
  }
}

// frontend/src/pages/Login.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ShieldAlert, Eye, EyeOff } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { authApi } from '../api/auth';
import Button from '../components/ui/Button';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPwd, setShowPwd] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const { data } = await authApi.login(email, password);
      login(data.token, data.employee);
      navigate('/', { replace: true });
    } catch {
      setError('Email o contraseña incorrectos');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 flex items-center justify-center p-4">
      <div className="w-full max-w-sm">
        {/* Logo */}
        <div className="flex flex-col items-center mb-8">
          <div className="w-14 h-14 bg-gray-900 rounded-2xl flex items-center justify-center mb-4 shadow-lg">
            <ShieldAlert size={28} className="text-white" />
          </div>
          <h1 className="text-2xl font-bold text-white">BlackList</h1>
          <p className="text-slate-400 text-sm mt-1">Panel de gestión</p>
        </div>

        {/* Card */}
        <div className="bg-white rounded-2xl shadow-2xl p-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-1">Iniciar sesión</h2>
          <p className="text-sm text-gray-500 mb-6">Accede con tus credenciales de empleado</p>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="form-label">Email</label>
              <input
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="form-input"
                placeholder="empleado@taller.com"
              />
            </div>

            <div>
              <label className="form-label">Contraseña</label>
              <div className="relative">
                <input
                  type={showPwd ? 'text' : 'password'}
                  required
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="form-input pr-10"
                  placeholder="••••••••"
                />
                <button
                  type="button"
                  onClick={() => setShowPwd((v) => !v)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  {showPwd ? <EyeOff size={16} /> : <Eye size={16} />}
                </button>
              </div>
            </div>

            {error && (
              <div className="bg-red-50 border border-red-200 rounded-lg px-4 py-3 text-sm text-red-700">
                {error}
              </div>
            )}

            <Button type="submit" variant="primary" loading={loading} className="w-full justify-center py-2.5">
              Entrar
            </Button>
          </form>
        </div>
      </div>
    </div>
  );
}
