// frontend/src/pages/Dashboard.tsx
import { useQuery } from '@tanstack/react-query';
import { ShieldAlert, FileText, AlertTriangle, Car, ArrowRight, Clock, Wrench } from 'lucide-react';
import { Link } from 'react-router-dom';
import { clientsApi } from '../api/clients';
import { rentalsApi } from '../api/rentals';
import { incidentsApi } from '../api/incidents';
import { useAuth } from '../context/AuthContext';
import Spinner from '../components/ui/Spinner';
import { ContractBadge, SeverityBadge, IncidentTypeBadge } from '../components/ui/Badge';
import type { RentalContract } from '../types';

export default function Dashboard() {
  const { employee } = useAuth();

  const { data: clients } = useQuery({
    queryKey: ['clients'],
    queryFn: () => clientsApi.getAll().then((r) => r.data),
  });

  const { data: rentals, isPending: rentalsLoading } = useQuery({
    queryKey: ['rentals'],
    queryFn: () => rentalsApi.getAll().then((r) => r.data),
  });

  const { data: incidents, isPending: incidentsLoading } = useQuery({
    queryKey: ['incidents'],
    queryFn: () => incidentsApi.getAll().then((r) => r.data),
  });

  const blacklistedClients = (clients ?? []).filter((c) => c.isBlacklisted);
  const activeRentals = (rentals ?? []).filter((r) => r.status === 'ACTIVE');
  const overdueRentals = (rentals ?? []).filter((r) => r.status === 'OVERDUE');
  const openIncidents = (incidents ?? []).filter((i) => !i.resolved);
  const criticalIncidents = openIncidents.filter((i) => i.severity === 'CRITICAL' || i.severity === 'HIGH');

  const urgentRentals = [...overdueRentals, ...activeRentals].slice(0, 6) as RentalContract[];
  const recentIncidents = openIncidents.slice(0, 5);

  return (
    <div className="p-8 space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">
            Bienvenido, {employee?.name?.split(' ')[0]}
          </h1>
          <p className="text-gray-400 text-sm mt-0.5">
            {new Date().toLocaleDateString('es-ES', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}
          </p>
        </div>

        {/* Alert summary strip */}
        <div className="flex items-center gap-3">
          {blacklistedClients.length > 0 && (
            <Link to="/blacklist" className="flex items-center gap-2 bg-gray-900 text-white px-4 py-2 rounded-xl text-sm font-medium hover:bg-gray-700 transition-colors">
              <ShieldAlert size={15} />
              {blacklistedClients.length} en lista negra
            </Link>
          )}
          {overdueRentals.length > 0 && (
            <Link to="/rentals" className="flex items-center gap-2 bg-gray-800 text-white px-4 py-2 rounded-xl text-sm font-medium hover:bg-gray-700 transition-colors">
              <Clock size={15} />
              {overdueRentals.length} vencido{overdueRentals.length !== 1 ? 's' : ''}
            </Link>
          )}
          {criticalIncidents.length > 0 && (
            <Link to="/incidents" className="flex items-center gap-2 bg-gray-700 text-white px-4 py-2 rounded-xl text-sm font-medium hover:bg-gray-600 transition-colors">
              <AlertTriangle size={15} />
              {criticalIncidents.length} incidencia{criticalIncidents.length !== 1 ? 's' : ''} crítica{criticalIncidents.length !== 1 ? 's' : ''}
            </Link>
          )}
        </div>
      </div>

      {/* Main grid */}
      <div className="grid grid-cols-3 gap-6">
        {/* Stat cards */}
        <div className="col-span-3 grid grid-cols-4 gap-4">
          <StatCard
            value={blacklistedClients.length}
            label="Lista negra"
            icon={ShieldAlert}
            dark
            to="/blacklist"
          />
          <StatCard
            value={activeRentals.length}
            label="Contratos activos"
            icon={FileText}
            to="/rentals"
          />
          <StatCard
            value={overdueRentals.length}
            label="Contratos vencidos"
            icon={Clock}
            alert={overdueRentals.length > 0}
            to="/rentals"
          />
          <StatCard
            value={openIncidents.length}
            label="Incidencias abiertas"
            icon={AlertTriangle}
            alert={openIncidents.length > 0}
            to="/incidents"
          />
        </div>

        {/* Contratos urgentes */}
        <div className="col-span-2 bg-white rounded-xl border border-gray-200 shadow-sm">
          <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
            <div className="flex items-center gap-2">
              <Car size={16} className="text-gray-500" />
              <h2 className="font-semibold text-gray-900">Contratos en curso</h2>
            </div>
            <Link to="/rentals" className="flex items-center gap-1 text-xs text-gray-500 hover:text-gray-900 font-medium">
              Ver todos <ArrowRight size={12} />
            </Link>
          </div>

          {rentalsLoading ? (
            <div className="p-6"><Spinner /></div>
          ) : urgentRentals.length === 0 ? (
            <p className="text-center py-10 text-sm text-gray-400">Sin contratos activos</p>
          ) : (
            <div className="divide-y divide-gray-50">
              {urgentRentals.map((r) => (
                <div key={r.id} className={`flex items-center gap-4 px-6 py-3.5 hover:bg-gray-50 transition-colors ${r.status === 'OVERDUE' ? 'bg-gray-50' : ''}`}>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-medium text-gray-900 truncate">{r.client.name}</p>
                      {r.client.isBlacklisted && (
                        <ShieldAlert size={12} className="text-gray-500 flex-shrink-0" />
                      )}
                    </div>
                    <p className="text-xs text-gray-400 truncate">
                      {r.car.brand} {r.car.model} · {r.car.licensePlate}
                    </p>
                  </div>
                  <div className="text-right flex-shrink-0">
                    <p className="text-xs text-gray-500">{new Date(r.endDate).toLocaleDateString('es-ES')}</p>
                  </div>
                  <ContractBadge status={r.status} />
                  <Link to={`/rentals/${r.id}`} className="text-gray-400 hover:text-gray-900 flex-shrink-0">
                    <ArrowRight size={14} />
                  </Link>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Incidencias abiertas */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm">
          <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
            <div className="flex items-center gap-2">
              <AlertTriangle size={16} className="text-gray-500" />
              <h2 className="font-semibold text-gray-900">Incidencias abiertas</h2>
            </div>
            <Link to="/incidents" className="flex items-center gap-1 text-xs text-gray-500 hover:text-gray-900 font-medium">
              Ver todas <ArrowRight size={12} />
            </Link>
          </div>

          {incidentsLoading ? (
            <div className="p-6"><Spinner /></div>
          ) : recentIncidents.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-10">
              <div className="w-10 h-10 bg-gray-100 rounded-xl flex items-center justify-center mb-2">
                <AlertTriangle size={18} className="text-gray-400" />
              </div>
              <p className="text-sm text-gray-400">Sin incidencias abiertas</p>
            </div>
          ) : (
            <div className="divide-y divide-gray-50">
              {recentIncidents.map((i) => (
                <div key={i.id} className="px-6 py-3.5">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <IncidentTypeBadge type={i.type} />
                    <SeverityBadge severity={i.severity} />
                  </div>
                  <p className="text-xs text-gray-700 truncate">{i.description}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{i.client?.name}</p>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Acceso rápido */}
        <div className="col-span-3 grid grid-cols-4 gap-3">
          {[
            { label: 'Nuevo cliente', to: '/clients/new', icon: Wrench },
            { label: 'Nuevo contrato', to: '/rentals/new', icon: FileText },
            { label: 'Registrar devolución', to: '/car-returns/new', icon: Car },
            { label: 'Nueva incidencia', to: '/incidents/new', icon: AlertTriangle },
          ].map(({ label, to, icon: Icon }) => (
            <Link
              key={to}
              to={to}
              className="flex items-center gap-2.5 px-4 py-3 rounded-xl border border-gray-200 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 hover:border-gray-300 transition-colors"
            >
              <Icon size={15} className="text-gray-500" />
              {label}
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}

function StatCard({
  value, label, icon: Icon, dark, alert, to,
}: {
  value: number;
  label: string;
  icon: React.ElementType;
  dark?: boolean;
  alert?: boolean;
  to: string;
}) {
  const base = dark
    ? 'bg-gray-900 text-white border-gray-800'
    : alert && value > 0
    ? 'bg-gray-800 text-white border-gray-700'
    : 'bg-white text-gray-900 border-gray-200';

  return (
    <Link to={to} className={`rounded-xl border shadow-sm p-5 flex items-center justify-between hover:opacity-90 transition-opacity ${base}`}>
      <div>
        <p className={`text-3xl font-bold`}>{value}</p>
        <p className={`text-xs mt-1 ${dark || (alert && value > 0) ? 'text-gray-400' : 'text-gray-500'}`}>{label}</p>
      </div>
      <Icon size={22} className={dark || (alert && value > 0) ? 'text-gray-500' : 'text-gray-300'} />
    </Link>
  );
}

// frontend/src/app/features/dashboard/dashboard.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DatePipe } from '@angular/common';
import { forkJoin } from 'rxjs';
import { LucideAngularModule, Users, Car, FileText, AlertTriangle, ShieldAlert, Wrench, Clock, OctagonAlert } from 'lucide-angular';
import { ClientsService } from '../../core/services/clients.service';
import { CarsService } from '../../core/services/cars.service';
import { RentalsService } from '../../core/services/rentals.service';
import { IncidentsService } from '../../core/services/incidents.service';
import { RepairsService } from '../../core/services/repairs.service';
import { SpinnerComponent } from '../../shared/components/spinner.component';
import { PageHeaderComponent } from '../../shared/components/page-header.component';
import type { RentalContract } from '../../core/models';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [RouterLink, LucideAngularModule, SpinnerComponent, PageHeaderComponent, DatePipe],
  template: `
    <app-page-header title="Panel" subtitle="Resumen general del sistema"></app-page-header>

    @if (loading()) {
      <app-spinner></app-spinner>
    } @else {
      <div class="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-4">
        <a routerLink="/clients" class="card p-5 hover:shadow-md transition-shadow cursor-pointer">
          <div class="flex items-center justify-between mb-3">
            <span class="text-xs font-medium text-gray-400 uppercase tracking-wide">Clientes</span>
            <lucide-icon [img]="Users" [size]="16" class="text-gray-300"></lucide-icon>
          </div>
          <p class="text-2xl font-bold text-gray-900">{{ stats().clients }}</p>
        </a>
        <a routerLink="/blacklist" class="card p-5 hover:shadow-md transition-shadow cursor-pointer">
          <div class="flex items-center justify-between mb-3">
            <span class="text-xs font-medium text-gray-400 uppercase tracking-wide">Lista Negra</span>
            <lucide-icon [img]="ShieldAlert" [size]="16" class="text-gray-300"></lucide-icon>
          </div>
          <p class="text-2xl font-bold text-gray-900">{{ stats().blacklisted }}</p>
        </a>
        <a routerLink="/cars" class="card p-5 hover:shadow-md transition-shadow cursor-pointer">
          <div class="flex items-center justify-between mb-3">
            <span class="text-xs font-medium text-gray-400 uppercase tracking-wide">Vehículos</span>
            <lucide-icon [img]="Car" [size]="16" class="text-gray-300"></lucide-icon>
          </div>
          <p class="text-2xl font-bold text-gray-900">{{ stats().cars }}</p>
        </a>
        <a routerLink="/rentals" class="card p-5 hover:shadow-md transition-shadow cursor-pointer">
          <div class="flex items-center justify-between mb-3">
            <span class="text-xs font-medium text-gray-400 uppercase tracking-wide">Contratos activos</span>
            <lucide-icon [img]="FileText" [size]="16" class="text-gray-300"></lucide-icon>
          </div>
          <p class="text-2xl font-bold text-gray-900">{{ stats().activeRentals }}</p>
        </a>
        <a routerLink="/incidents" class="card p-5 hover:shadow-md transition-shadow cursor-pointer">
          <div class="flex items-center justify-between mb-3">
            <span class="text-xs font-medium text-gray-400 uppercase tracking-wide">Incidencias</span>
            <lucide-icon [img]="AlertTriangle" [size]="16" class="text-gray-300"></lucide-icon>
          </div>
          <p class="text-2xl font-bold text-gray-900">{{ stats().unresolvedIncidents }}</p>
        </a>
        <a routerLink="/repairs" class="card p-5 hover:shadow-md transition-shadow cursor-pointer">
          <div class="flex items-center justify-between mb-3">
            <span class="text-xs font-medium text-gray-400 uppercase tracking-wide">Reparaciones</span>
            <lucide-icon [img]="Wrench" [size]="16" class="text-gray-300"></lucide-icon>
          </div>
          <p class="text-2xl font-bold text-gray-900">{{ stats().pendingRepairs }}</p>
        </a>
      </div>

      <div class="grid grid-cols-1 xl:grid-cols-2 gap-6 mt-6">
        <!-- Pendientes de devolver -->
        <div class="card p-5">
          <div class="flex items-center gap-2 mb-4">
            <lucide-icon [img]="Clock" [size]="16" class="text-blue-500"></lucide-icon>
            <h2 class="text-sm font-semibold text-gray-700">Devoluciones de hoy</h2>
            <span class="ml-auto text-xs font-medium bg-blue-50 text-blue-600 px-2 py-0.5 rounded-full">{{ activeRentals().length }}</span>
          </div>
          @if (activeRentals().length === 0) {
            <p class="text-sm text-gray-400 text-center py-6">No hay devoluciones previstas para hoy</p>
          } @else {
            <div class="overflow-x-auto">
              <table class="w-full text-sm">
                <thead>
                  <tr class="text-xs text-gray-400 border-b border-gray-100">
                    <th class="text-left pb-2 font-medium">Vehículo</th>
                    <th class="text-left pb-2 font-medium">Cliente</th>
                    <th class="text-left pb-2 font-medium">Fecha fin</th>
                    <th class="pb-2"></th>
                  </tr>
                </thead>
                <tbody>
                  @for (r of activeRentals(); track r.id) {
                    <tr class="border-b border-gray-50 last:border-0">
                      <td class="py-2 pr-3 font-medium text-gray-900">
                        {{ r.car.brand }} {{ r.car.model }}
                        <span class="block text-xs text-gray-400 font-normal">{{ r.car.licensePlate }}</span>
                      </td>
                      <td class="py-2 pr-3 text-gray-600">{{ r.client.name }}</td>
                      <td class="py-2 pr-3 text-gray-600">{{ r.endDate | date:'dd/MM/yyyy' }}</td>
                      <td class="py-2 text-right">
                        <a [routerLink]="['/rentals', r.id]" class="text-xs text-blue-500 hover:underline">Ver</a>
                      </td>
                    </tr>
                  }
                </tbody>
              </table>
            </div>
          }
        </div>

        <!-- Fuera de plazo -->
        <div class="card p-5">
          <div class="flex items-center gap-2 mb-4">
            <lucide-icon [img]="OctagonAlert" [size]="16" class="text-red-500"></lucide-icon>
            <h2 class="text-sm font-semibold text-gray-700">Fuera de plazo</h2>
            <span class="ml-auto text-xs font-medium bg-red-50 text-red-600 px-2 py-0.5 rounded-full">{{ overdueRentals().length }}</span>
          </div>
          @if (overdueRentals().length === 0) {
            <p class="text-sm text-gray-400 text-center py-6">No hay vehículos fuera de plazo</p>
          } @else {
            <div class="overflow-x-auto">
              <table class="w-full text-sm">
                <thead>
                  <tr class="text-xs text-gray-400 border-b border-gray-100">
                    <th class="text-left pb-2 font-medium">Vehículo</th>
                    <th class="text-left pb-2 font-medium">Cliente</th>
                    <th class="text-left pb-2 font-medium">Venció el</th>
                    <th class="pb-2"></th>
                  </tr>
                </thead>
                <tbody>
                  @for (r of overdueRentals(); track r.id) {
                    <tr class="border-b border-gray-50 last:border-0">
                      <td class="py-2 pr-3 font-medium text-gray-900">
                        {{ r.car.brand }} {{ r.car.model }}
                        <span class="block text-xs text-gray-400 font-normal">{{ r.car.licensePlate }}</span>
                      </td>
                      <td class="py-2 pr-3 text-gray-600">{{ r.client.name }}</td>
                      <td class="py-2 pr-3 text-red-500 font-medium">{{ r.endDate | date:'dd/MM/yyyy' }}</td>
                      <td class="py-2 text-right">
                        <a [routerLink]="['/rentals', r.id]" class="text-xs text-blue-500 hover:underline">Ver</a>
                      </td>
                    </tr>
                  }
                </tbody>
              </table>
            </div>
          }
        </div>
      </div>
    }
  `,
})
export class DashboardComponent implements OnInit {
  private clientsService = inject(ClientsService);
  private carsService = inject(CarsService);
  private rentalsService = inject(RentalsService);
  private incidentsService = inject(IncidentsService);
  private repairsService = inject(RepairsService);

  readonly Users = Users;
  readonly ShieldAlert = ShieldAlert;
  readonly Car = Car;
  readonly FileText = FileText;
  readonly AlertTriangle = AlertTriangle;
  readonly Wrench = Wrench;
  readonly Clock = Clock;
  readonly OctagonAlert = OctagonAlert;

  loading = signal(true);
  stats = signal({ clients: 0, blacklisted: 0, cars: 0, activeRentals: 0, unresolvedIncidents: 0, pendingRepairs: 0 });
  activeRentals = signal<RentalContract[]>([]);
  overdueRentals = signal<RentalContract[]>([]);

  ngOnInit() {
    forkJoin({
      clients: this.clientsService.getAll(),
      cars: this.carsService.getAll(),
      rentals: this.rentalsService.getAll({ status: 'ACTIVE' }),
      overdue: this.rentalsService.getAll({ status: 'OVERDUE' }),
      incidents: this.incidentsService.getAll({ resolved: false }),
      repairs: this.repairsService.getAll({ status: 'PENDING' }),
    }).subscribe({
      next: ({ clients, cars, rentals, overdue, incidents, repairs }) => {
        this.stats.set({
          clients: clients.length,
          blacklisted: clients.filter(c => c.isBlacklisted).length,
          cars: cars.length,
          activeRentals: rentals.length,
          unresolvedIncidents: incidents.length,
          pendingRepairs: repairs.length,
        });
        const today = new Date().toISOString().slice(0, 10);
        this.activeRentals.set(rentals.filter(r => r.endDate.slice(0, 10) === today));
        this.overdueRentals.set(overdue);
        this.loading.set(false);
      },
      error: () => this.loading.set(false),
    });
  }
}
